INSERT INTO DEPARTMENT VALUES ('AD','Administration');
INSERT INTO DEPARTMENT VALUES ('IT','Information technology');
INSERT INTO DEPARTMENT VALUES ('HD','Help Desk');
INSERT INTO DEPARTMENT VALUES ('HR','Human Resource');
INSERT INTO DEPARTMENT VALUES ('OP','Operation');